# Generated by Django 5.0.14 on 2026-09-12 12:38

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0002_feetransaction_gateway_and_more'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=payments.models.generate_reference, editable=False, max_length=64, unique=True)),
                ('gateway', models.CharField(default='paychangu', max_length=30)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('checkout_url', models.URLField(blank=True)),
                ('raw_initiation_response', models.JSONField(blank=True, null=True)),
                ('raw_webhook_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_transaction', models.OneToOneField(blank=True, help_text='The internal receipt this gateway payment was posted as, once confirmed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='fees.feetransaction')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_b6726a_idx'), models.Index(fields=['gateway_reference'], name='payments_pa_gateway_3df281_idx')],
            },
        ),
    ]
