# Generated by Django 5.2.17 on 2026-09-14 14:49

import django.db.models.deletion
import djmoney.models.fields
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=payments.models.generate_reference, editable=False, max_length=64, unique=True)),
                ('gateway', models.CharField(default='paychangu', max_length=30)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('MWK', 'Malawian Kwacha'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar')], default='MWK', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('checkout_url', models.URLField(blank=True)),
                ('raw_initiation_response', models.JSONField(blank=True, null=True)),
                ('raw_webhook_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_transaction', models.OneToOneField(blank=True, help_text='The internal receipt this gateway payment was posted as, once confirmed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='fees.feetransaction')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
