# Generated by Django 5.0.14 on 2026-09-12 05:43

import accounts.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=15)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_phone', models.CharField(blank=True, db_index=True, max_length=20, validators=[accounts.models.malawi_phone_validator])),
                ('address', models.TextField(blank=True)),
                ('class_name', models.CharField(db_index=True, help_text="e.g. 'Form 3'", max_length=10)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('fees_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('average_grade', models.CharField(blank=True, default='N/A', max_length=3)),
                ('enrolled_on', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical student',
                'verbose_name_plural': 'historical students',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=15, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_phone', models.CharField(blank=True, db_index=True, max_length=20, validators=[accounts.models.malawi_phone_validator])),
                ('address', models.TextField(blank=True)),
                ('class_name', models.CharField(db_index=True, help_text="e.g. 'Form 3'", max_length=10)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('inactive', 'Inactive')], default='active', max_length=12)),
                ('fees_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('average_grade', models.CharField(blank=True, default='N/A', max_length=3)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['class_name', 'stream', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='GuardianContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, validators=[accounts.models.malawi_phone_validator])),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('uncle_aunt', 'Uncle/Aunt'), ('guardian', 'Legal Guardian'), ('other', 'Other')], default='guardian', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('linked_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_contact_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
