# Generated by Django 5.2.17 on 2026-09-14 14:49

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('term', models.CharField(default='Term 1', max_length=30)),
                ('total_amount_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('MWK', 'Malawian Kwacha'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar')], default='MWK', editable=False, max_length=3)),
                ('total_amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('MWK', 'Malawian Kwacha'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar')], default='MWK', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online (Card/Mobile via gateway)')], default='Mobile Money', max_length=20)),
                ('receipt_no', models.CharField(max_length=30, unique=True)),
                ('gateway', models.CharField(blank=True, max_length=30)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('discount', 'Discount (e.g. sibling, staff child)'), ('bursary', 'Bursary'), ('scholarship', 'Scholarship')], default='discount', max_length=15)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or a fixed MK amount.', max_digits=12)),
                ('sponsor_name', models.CharField(blank=True, help_text='NGO, government, church, etc.', max_length=150)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
