# Generated by Django 5.0.14 on 2026-09-12 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='gateway',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='reversal_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='method',
            field=models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online (Card/Mobile via gateway)')], default='Mobile Money', max_length=20),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('discount', 'Discount (e.g. sibling, staff child)'), ('bursary', 'Bursary'), ('scholarship', 'Scholarship')], default='discount', max_length=15)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or a fixed MK amount.', max_digits=12)),
                ('sponsor_name', models.CharField(blank=True, help_text='NGO, government, church, etc.', max_length=150)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_approved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='students.student')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
