# Generated by Django 5.0.14 on 2026-09-12 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
        ('syllabus', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam', models.CharField(choices=[('Mid-Term', 'Mid-Term'), ('Final Exam', 'Final Exam'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment')], default='Mid-Term', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=3)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('maneb_grade', models.ForeignKey(blank=True, help_text='Auto-mapped MANEB grade (1-9) from the score.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.manebgradescale')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='students.student')),
                ('syllabus_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='syllabus.paper')),
                ('syllabus_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='syllabus.subject')),
                ('syllabus_topic', models.ForeignKey(blank=True, help_text='Which syllabus topic was this assessment on?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='syllabus.syllabustopic')),
            ],
            options={
                'ordering': ['-recorded_on'],
            },
        ),
    ]
