# Generated by Django 5.2.17 on 2026-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam', models.CharField(choices=[('Mid-Term', 'Mid-Term'), ('Final Exam', 'Final Exam'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment')], default='Mid-Term', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=3)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_on'],
            },
        ),
    ]
