# Generated by Django 5.2.17 on 2026-09-14 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('students', '0001_initial'),
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='maneb_grade',
            field=models.ForeignKey(blank=True, help_text='Auto-mapped MANEB grade (1-9) from the score.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.manebgradescale'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='syllabus_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='syllabus.paper'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='syllabus_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='syllabus.subject'),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='syllabus_topic',
            field=models.ForeignKey(blank=True, help_text='Which syllabus topic was this assessment on?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_records', to='syllabus.syllabustopic'),
        ),
    ]
