# Generated by Django 5.2.17 on 2026-09-15 06:47

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('account_activated', 'Account Activated'), ('account_deactivated', 'Account Deactivated'), ('account_created', 'Account Created'), ('permission_denied', 'Permission Denied'), ('invitation_sent', 'Invitation Sent'), ('invitation_claimed', 'Invitation Claimed'), ('invitation_revoked', 'Invitation Revoked'), ('invitation_expired', 'Invitation Expired'), ('approval_requested', 'Approval Requested'), ('approval_granted', 'Approval Granted'), ('approval_rejected', 'Approval Rejected')], max_length=25)),
                ('method', models.CharField(blank=True, choices=[('invitation', 'Invitation'), ('direct', 'Direct Creation'), ('import', 'Bulk Import'), ('self_registration', 'Self-Registration')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=accounts.models.generate_verification_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=accounts.models.generate_verification_token, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('student', 'Student Account'), ('parent', 'Parent / Guardian Account'), ('teacher', 'Teacher Account'), ('staff', 'Non-teaching Staff Account'), ('admin', 'Administrator Account'), ('bursar', 'Bursar / Accountant Account'), ('auditor', 'External Auditor Account')], max_length=20)),
                ('proposed_username', models.CharField(blank=True, max_length=150)),
                ('invited_first_name', models.CharField(blank=True, max_length=150)),
                ('invited_last_name', models.CharField(blank=True, max_length=150)),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('invited_phone', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'SMS + Email'), ('manual', 'Manual (printed claim sheet)')], max_length=10)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Password histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('staff', 'Staff')], default='student', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ny', 'Chichewa')], default='en', max_length=10)),
                ('email_verified', models.BooleanField(default=True)),
                ('phone_verified', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Who approved this account (Head Teacher for teacher/staff; null for implicit approvals).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who created this account (Registry Clerk, HR Officer, Head Teacher, or self for parent self-registration).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': [('create_account', 'Can create user accounts'), ('create_student_account', 'Can create Student accounts'), ('create_parent_account', 'Can create Parent accounts'), ('create_teacher_account', 'Can create Teacher accounts'), ('create_staff_account', 'Can create Staff accounts'), ('create_admin_account', 'Can create Administrator accounts'), ('create_bursar_account', 'Can create Bursar/Accountant accounts'), ('create_auditor_account', 'Can create External Auditor accounts'), ('create_high_privilege_account', 'Can create high-privilege accounts (admin/bursar/auditor)'), ('approve_account_creation', 'Can approve pending account-creation requests')],
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('teacher', 'Teacher Account'), ('staff', 'Non-teaching Staff Account')], max_length=20)),
                ('proposed_username', models.CharField(max_length=150)),
                ('proposed_first_name', models.CharField(blank=True, max_length=150)),
                ('proposed_last_name', models.CharField(blank=True, max_length=150)),
                ('proposed_email', models.EmailField(blank=True, max_length=254)),
                ('proposed_phone', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Invitation Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
