# Generated by Django 5.2.15 on 2026-09-08 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Login Log', 'verbose_name_plural': 'Login Logs'},
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locked_until',
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed', 'Failed')], default='login', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(default=8092026, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
