# Generated by Django 5.2.17 on 2026-10-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('account_activated', 'Account Activated'), ('account_deactivated', 'Account Deactivated'), ('account_created', 'Account Created'), ('permission_denied', 'Permission Denied'), ('invitation_sent', 'Invitation Sent'), ('invitation_claimed', 'Invitation Claimed'), ('invitation_revoked', 'Invitation Revoked'), ('invitation_expired', 'Invitation Expired'), ('approval_requested', 'Approval Requested'), ('approval_granted', 'Approval Granted'), ('approval_rejected', 'Approval Rejected'), ('tcm_reminder_sent', 'TCM License Reminder Sent')], max_length=25),
        ),
    ]
