# Generated by Django 5.2.15 on 2026-09-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_loginlog_options_remove_loginlog_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
