# Generated by Django 5.2.17 on 2026-09-14 14:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTeacher',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, db_index=True, max_length=15)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(help_text='Primary subject / specialization', max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=10)),
                ('hired_on', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical teacher',
                'verbose_name_plural': 'historical teachers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, db_index=True, max_length=15, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(help_text='Primary subject / specialization', max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=10)),
                ('hired_on', models.DateField(auto_now_add=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='teachers.subject')),
                ('syllabus_papers', models.ManyToManyField(blank=True, help_text='Specific papers this teacher is qualified to teach (e.g. Physics Paper II - practical).', related_name='teachers_assigned', to='syllabus.paper')),
                ('syllabus_subjects', models.ManyToManyField(blank=True, help_text='MANEB subjects (with official codes) this teacher is qualified to teach.', related_name='teachers_assigned', to='syllabus.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('subject', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(blank=True, max_length=150)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date_obtained'],
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='teachers_te_status_cc7a79_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['subject'], name='teachers_te_subject_051332_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classassignment',
            unique_together={('teacher', 'class_name', 'stream', 'subject')},
        ),
    ]
