# Generated by Django 5.2.17 on 2026-10-08 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_grade', models.CharField(max_length=10)),
                ('to_grade', models.CharField(max_length=10)),
                ('promoted_at', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-promoted_at'],
            },
        ),
        migrations.CreateModel(
            name='TCMLicenseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewed_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('receipt_number', models.CharField(max_length=50)),
                ('renewal_fee_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document', models.FileField(blank=True, upload_to='tcm_licenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-renewed_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('msce', 'MSCE'), ('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('teacher_cert', "Teacher's Certificate (2-year TTC)"), ('diploma_ed', 'Diploma in Education'), ('bed', 'Bachelor of Education (B.Ed.)'), ('degree_uce', 'Degree + University Certificate of Education (UCE)'), ('pgde', 'Postgraduate Diploma in Education'), ('other', 'Other')], max_length=30)),
                ('institution', models.CharField(max_length=200)),
                ('year_obtained', models.PositiveSmallIntegerField()),
                ('certificate', models.FileField(blank=True, upload_to='teacher_certs/')),
                ('verified', models.BooleanField(default=False, help_text='Set once an administrator has checked the certificate scan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year_obtained'],
            },
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='academic_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('government', 'Government (TSC)'), ('private', 'Private (school-employed)'), ('church', 'Church / mission'), ('volunteer', 'Volunteer')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='government_grade',
            field=models.CharField(blank=True, choices=[('PT4', 'PT4 (entry)'), ('PT3', 'PT3'), ('PT2', 'PT2 (headship)'), ('PT1', 'PT1 (headship)'), ('TI', 'TI (entry)'), ('TJ', 'TJ')], help_text='Leave blank for private / church / volunteer posts.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='highest_academic_qualification',
            field=models.CharField(blank=True, choices=[('msce', 'MSCE'), ('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD')], max_length=30),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='professional_institution',
            field=models.CharField(blank=True, help_text='e.g. Nalikule TTC, Domasi College, Chancellor College, Mzuzu University.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='professional_qualification',
            field=models.CharField(blank=True, choices=[('teacher_cert', "Teacher's Certificate (2-year TTC)"), ('diploma_ed', 'Diploma in Education'), ('bed', 'Bachelor of Education (B.Ed.)'), ('degree_uce', 'Degree + University Certificate of Education (UCE)'), ('pgde', 'Postgraduate Diploma in Education'), ('none', 'None — unqualified')], max_length=50),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='tcm_license_expiry',
            field=models.DateField(blank=True, db_index=True, help_text='License must be renewed — the system warns 60/30/7 days before expiry.', null=True),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='tcm_registration_number',
            field=models.CharField(blank=True, db_index=True, help_text='Teaching Council of Malawi registration number.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='tcm_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('provisional', 'Provisional'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('not_registered', 'Not registered')], db_index=True, default='not_registered', help_text='Registered/Provisional are the only statuses that permit class assignment.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='teaching_level',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('both', 'Both')], default='secondary', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalteacher',
            name='year_qualified',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='academic_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('government', 'Government (TSC)'), ('private', 'Private (school-employed)'), ('church', 'Church / mission'), ('volunteer', 'Volunteer')], max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='government_grade',
            field=models.CharField(blank=True, choices=[('PT4', 'PT4 (entry)'), ('PT3', 'PT3'), ('PT2', 'PT2 (headship)'), ('PT1', 'PT1 (headship)'), ('TI', 'TI (entry)'), ('TJ', 'TJ')], help_text='Leave blank for private / church / volunteer posts.', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='highest_academic_qualification',
            field=models.CharField(blank=True, choices=[('msce', 'MSCE'), ('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD')], max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='professional_institution',
            field=models.CharField(blank=True, help_text='e.g. Nalikule TTC, Domasi College, Chancellor College, Mzuzu University.', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='professional_qualification',
            field=models.CharField(blank=True, choices=[('teacher_cert', "Teacher's Certificate (2-year TTC)"), ('diploma_ed', 'Diploma in Education'), ('bed', 'Bachelor of Education (B.Ed.)'), ('degree_uce', 'Degree + University Certificate of Education (UCE)'), ('pgde', 'Postgraduate Diploma in Education'), ('none', 'None — unqualified')], max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tcm_license_expiry',
            field=models.DateField(blank=True, db_index=True, help_text='License must be renewed — the system warns 60/30/7 days before expiry.', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tcm_registration_number',
            field=models.CharField(blank=True, help_text='Teaching Council of Malawi registration number.', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tcm_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('provisional', 'Provisional'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('not_registered', 'Not registered')], db_index=True, default='not_registered', help_text='Registered/Provisional are the only statuses that permit class assignment.', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_level',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('both', 'Both')], default='secondary', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='year_qualified',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['tcm_status'], name='teachers_te_tcm_sta_d07ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['tcm_license_expiry'], name='teachers_te_tcm_lic_8c8182_idx'),
        ),
        migrations.AddField(
            model_name='gradepromotion',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_promotions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradepromotion',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_promotions', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='tcmlicenserenewal',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_renewals', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='teacherqualification',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='gradepromotion',
            index=models.Index(fields=['teacher', 'promoted_at'], name='teachers_gr_teacher_ed034c_idx'),
        ),
        migrations.AddIndex(
            model_name='tcmlicenserenewal',
            index=models.Index(fields=['teacher', 'expires_at'], name='teachers_tc_teacher_dc6f88_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherqualification',
            index=models.Index(fields=['teacher', 'qualification_type'], name='teachers_te_teacher_9bbd38_idx'),
        ),
    ]
