# Generated by Django 5.0.14 on 2026-09-12 05:43

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('exam_year', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('date_effective', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-exam_year'],
            },
        ),
        migrations.CreateModel(
            name='ManebGradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(help_text='Distinction / Credit / Pass / Fail', max_length=30)),
                ('gce_equivalent', models.BooleanField(default=False, help_text="Grades 1-6 are GCE 'O' Level equivalent")),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['grade_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='MANEB subject code, e.g., M131 for Mathematics', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^M\\d{3}$', 'Code must be in format M### (e.g., M131).')])),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sciences', 'Sciences'), ('languages', 'Languages'), ('humanities', 'Humanities'), ('technical', 'Technical/Vocational'), ('business', 'Business & Commerce'), ('maths', 'Mathematics'), ('arts', 'Creative Arts')], max_length=20)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TopicCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('stream', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('is_covered', models.BooleanField(default=False)),
                ('covered_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSubject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='MANEB subject code, e.g., M131 for Mathematics', max_length=10, validators=[django.core.validators.RegexValidator('^M\\d{3}$', 'Code must be in format M### (e.g., M131).')])),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sciences', 'Sciences'), ('languages', 'Languages'), ('humanities', 'Humanities'), ('technical', 'Technical/Vocational'), ('business', 'Business & Commerce'), ('maths', 'Mathematics'), ('arts', 'Creative Arts')], max_length=20)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical subject',
                'verbose_name_plural': 'historical subjects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g., I, II, III', max_length=10)),
                ('title', models.CharField(blank=True, help_text="e.g., 'Theory paper'", max_length=150)),
                ('paper_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('coursework', 'Coursework'), ('oral', 'Oral/Aural'), ('project', 'Project')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('total_marks', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, help_text='Rules/format from MANEB syllabus')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='syllabus.subject')),
            ],
            options={
                'ordering': ['subject', 'number'],
            },
        ),
        migrations.CreateModel(
            name='GradeDescriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_band', models.CharField(choices=[('pass', 'Pass'), ('credit', 'Credit'), ('distinction', 'Distinction')], max_length=20)),
                ('descriptor', models.TextField(help_text='The abilities candidates must demonstrate at this band')),
                ('paper', models.ForeignKey(blank=True, help_text='Some subjects publish descriptors per paper', null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.paper')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_descriptors', to='syllabus.subject')),
            ],
            options={
                'ordering': ['subject', 'paper', 'grade_band'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_element', models.CharField(blank=True, help_text="e.g., 'Functions and Graphs'", max_length=150)),
                ('code', models.CharField(blank=True, db_index=True, help_text="Syllabus code like '3.3.1.1'", max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('paper', models.ForeignKey(blank=True, help_text='Paper(s) this topic is tested in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='syllabus.paper')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='syllabus.syllabustopic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.subject')),
            ],
            options={
                'ordering': ['subject', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSyllabusTopic',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('core_element', models.CharField(blank=True, help_text="e.g., 'Functions and Graphs'", max_length=150)),
                ('code', models.CharField(blank=True, db_index=True, help_text="Syllabus code like '3.3.1.1'", max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(blank=True, db_constraint=False, help_text='Paper(s) this topic is tested in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='syllabus.paper')),
                ('subject', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='syllabus.subject')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='syllabus.syllabustopic')),
            ],
            options={
                'verbose_name': 'historical syllabus topic',
                'verbose_name_plural': 'historical syllabus topics',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AssessmentObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="e.g., 'find images of polynomial functions'")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='syllabus.syllabustopic')),
            ],
            options={
                'ordering': ['topic', 'order'],
            },
        ),
    ]
