# Generated by Django 5.2.17 on 2026-09-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccoverage',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_coverage', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='topiccoverage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='syllabus.syllabustopic'),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('subject', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='gradedescriptor',
            unique_together={('subject', 'paper', 'grade_band')},
        ),
        migrations.AddIndex(
            model_name='syllabustopic',
            index=models.Index(fields=['subject', 'is_active'], name='syllabus_sy_subject_823d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabustopic',
            index=models.Index(fields=['tree_id', 'lft'], name='syllabus_syllabustopic_tre74f5'),
        ),
        migrations.AlterUniqueTogether(
            name='topiccoverage',
            unique_together={('topic', 'teacher', 'class_name', 'stream')},
        ),
    ]
