# Generated by Django 5.2.17 on 2026-10-08 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_initial'),
        ('teachers', '0002_gradepromotion_tcmlicenserenewal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={'ordering': ['-exam_year', 'level']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['level', 'code']},
        ),
        migrations.AddField(
            model_name='examsession',
            name='level',
            field=models.CharField(choices=[('JCE', 'Junior Certificate of Education'), ('MSCE', 'Malawi School Certificate of Education')], db_index=True, default='MSCE', help_text='Which national examination this session belongs to.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalsubject',
            name='level',
            field=models.CharField(choices=[('JCE', 'Junior Certificate of Education'), ('MSCE', 'Malawi School Certificate of Education')], db_index=True, default='MSCE', help_text='Which national examination this subject belongs to.', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('JCE', 'Junior Certificate of Education'), ('MSCE', 'Malawi School Certificate of Education')], db_index=True, default='MSCE', help_text='Which national examination this subject belongs to.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalsubject',
            name='code',
            field=models.CharField(db_index=True, help_text='MANEB subject code, e.g., M131 (MSCE Mathematics) or J131 (JCE Mathematics)', max_length=10, validators=[django.core.validators.RegexValidator('^[MJ]\\d{3}$', 'Code must be M### for MSCE or J### for JCE (e.g., M131, J131).')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(db_index=True, help_text='MANEB subject code, e.g., M131 (MSCE Mathematics) or J131 (JCE Mathematics)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[MJ]\\d{3}$', 'Code must be M### for MSCE or J### for JCE (e.g., M131, J131).')]),
        ),
        migrations.AlterField(
            model_name='syllabustopic',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Syllabus code like '3.3.1.1' or 'J-MATH-01-01'", max_length=20),
        ),
        migrations.AddIndex(
            model_name='assessmentobjective',
            index=models.Index(fields=['topic', 'is_active'], name='syllabus_as_topic_i_170a52_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['level', 'is_current'], name='syllabus_ex_level_5bc98f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['level', 'category', 'is_active'], name='syllabus_su_level_7c90a7_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['level', 'is_active'], name='syllabus_su_level_268d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabustopic',
            index=models.Index(fields=['subject', 'code'], name='syllabus_sy_subject_e65d65_idx'),
        ),
        migrations.AddIndex(
            model_name='topiccoverage',
            index=models.Index(fields=['teacher', 'is_covered'], name='syllabus_to_teacher_51a60d_idx'),
        ),
        migrations.AddIndex(
            model_name='topiccoverage',
            index=models.Index(fields=['teacher', 'class_name', 'stream'], name='syllabus_to_teacher_3b79a8_idx'),
        ),
    ]
